version: "3"

services:
  keydb:
    image: docker.io/eqalpha/keydb:latest
    command: ["--requirepass", "changemeplease!!"]

  marshal-0:
    image: ghcr.io/espressosystems/push-cdn/marshal:latest
    command: ["-d", "redis://:changemeplease!!@keydb:6379"]

  broker-0:
    image: ghcr.io/espressosystems/push-cdn/broker:latest
    command: ["-d", "redis://:changemeplease!!@keydb:6379"]

  broker-1:
    image: ghcr.io/espressosystems/push-cdn/broker:latest
    command: ["-d", "redis://:changemeplease!!@keydb:6379"]
