version: "0.5"

processes:
  redis:
    command: echo 'requirepass changeme!' | keydb-server - --save "" --appendonly no

  marshal_0:
    command: cargo run --package marshal --features insecure --no-default-features -- -d "redis://:changeme!@127.0.0.1:6379"
    depends_on:
      redis:
        condition: process_started

  broker_0:
    command: cargo run --package broker --features insecure --no-default-features -- --public-advertise-address 127.0.0.1:8083 --private-bind-port 8082 --public-bind-port 8083 -d "redis://:changeme!@127.0.0.1:6379"
    depends_on:
      redis:
        condition: process_started

  broker_1:
    command: cargo run --package broker --features insecure --no-default-features -- --metrics-port=9091 --public-advertise-address 127.0.0.1:8085 --private-bind-port 8084 --public-bind-port 8085 -d "redis://:changeme!@127.0.0.1:6379"
    depends_on:
      redis:
        condition: process_started

  client_0:
    command: cargo run --bin client --features insecure --no-default-features -- --id 0
    depends_on:
      marshal_0:
        condition: process_started
  
  client_1:
    command: cargo run --bin client --features insecure --no-default-features -- --id 1
    depends_on:
      marshal_0:
        condition: process_started
  