version: "0.5"

processes:
  redis:
    command: echo 'requirepass changeme!' | keydb-server - --save "" --appendonly no

  marshal_0:
    command: cargo run --package marshal --features insecure --no-default-features -- -d "redis://:changeme!@127.0.0.1:6379"
    depends_on:
      redis:
        condition: process_started

  broker_0:
    command: cargo run --package broker --features insecure --no-default-features -- -b 8082 -u 8083 -d "redis://:changeme!@127.0.0.1:6379"
    depends_on:
      redis:
        condition: process_started

  broker_1:
    command: cargo run --package broker --features insecure --no-default-features -- -b 8084 -u 8085 -d "redis://:changeme!@127.0.0.1:6379"
    depends_on:
      redis:
        condition: process_started

  client_0:
    command: cargo run --bin client --features insecure --no-default-features -- --id 0
    depends_on:
      marshal_0:
        condition: process_started
  
  client_1:
    command: cargo run --bin client --features insecure --no-default-features -- --id 1
    depends_on:
      marshal_0:
        condition: process_started
  