version: "0.5"

processes:
  redis:
    command: echo 'requirepass changeme!' | keydb-server - --save "" --appendonly no

  marshal_0:
    command: cargo run --package cdn-marshal --release -- -d "redis://:changeme!@localhost:6379"

  broker_0:
    command: cargo run --package cdn-broker --release -- --public-advertise-address 127.0.0.1:8083 --private-bind-port 8082 --public-bind-port 8083 -d "redis://:changeme!@localhost:6379"

  broker_1:
    command: cargo run --package cdn-broker --release -- --metrics-port=9091 --public-advertise-address 127.0.0.1:8085 --private-bind-port 8084 --public-bind-port 8085 -d "redis://:changeme!@localhost:6379"

  client_0:
    command: cargo run --bin cdn-client --release
    depends_on:
      marshal_0:
        condition: process_started
  
  client_1:
    command: cargo run --bin cdn-client --release
    depends_on:
      marshal_0:
        condition: process_started