version: "0.5"

processes:
  # redis:
  #   command: echo 'requirepass changeme!' | keydb-server - --save "" --appendonly no

  marshal_0:
    command: cargo run --package marshal --release --features insecure --features local_discovery --no-default-features -- -d "test.sqlite"

  broker_0:
    command: cargo run --package broker --release --features insecure --features local_discovery --no-default-features -- --public-advertise-address 127.0.0.1:8083 --private-bind-port 8082 --public-bind-port 8083 -d "test.sqlite"

  broker_1:
    command: cargo run --package broker --release --features insecure --features local_discovery --no-default-features -- --metrics-port=9091 --public-advertise-address 127.0.0.1:8085 --private-bind-port 8084 --public-bind-port 8085 -d "test.sqlite"

  client_0:
    command: cargo run --bin client --release --features insecure --features local_discovery --features runtime-tokio --no-default-features -- --id 0
    depends_on:
      marshal_0:
        condition: process_started
  
  client_1:
    command: cargo run --bin client --release --features insecure --features local_discovery --features runtime-tokio --no-default-features -- --id 1
    depends_on:
      marshal_0:
        condition: process_started
  