version: "0.5"

processes:
  redis:
    command: echo 'requirepass changeme!' | keydb-server - --save "" --appendonly no

  marshal_0:
    command: cargo run --package cdn-marshal --release -- --metrics-port=8080 -d "redis://:changeme!@localhost:6379"

  broker_0:
    command: cargo run --package cdn-broker --release -- -d "redis://:changeme!@localhost:6379"

  broker_1:
    command: cargo run --package cdn-broker --release -- 
      --public-bind-address 0.0.0.0:8085
      --public-advertise-address 127.0.0.1:8085
      --private-bind-address 0.0.0.0:8085
      --private-advertise-address 127.0.0.1:8085
      -d "redis://:changeme!@localhost:6379"

  client_0:
    command: cargo run --bin cdn-client --release -- -m "127.0.0.1:1737"
    depends_on:
      marshal_0:
        condition: process_started