[package]
name = "broker-proto"
version = "0.1.0"
edition = "2021"

[build-dependencies]
capnpc = "0.19.0"

[dependencies]
capnp = "0.19.1"
thiserror = "1.0.56"
quinn = "0.10.2"
tokio.workspace = true