[package]
name = "broker"
version = "0.1.0"
edition = "2021"

description = "Defines the broker server, which is responsible for routing messages from clients"

[dependencies]
jf-primitives.workspace = true
proto.path = "../proto"
tokio.workspace = true
tracing.workspace = true
ark-serialize.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
local-ip-address = "0.5.7"
slotmap = "1.0.7"
delegate = "0.12.0"
paste = "1.0.14"