[package]
name = "broker"
version = "0.1.0"
edition = "2021"

description = "Defines the broker server, which is responsible for routing messages from clients"

[dependencies]
jf-primitives.workspace = true
proto.path = "../proto"
tokio.workspace = true
tracing.workspace = true
ark-serialize.workspace = true
tracing-subscriber.workspace = true
parking_lot = "0.12.1"
clap.workspace = true
local-ip-address = "0.5.7"