name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install capnproto
      - run: cargo fmt

      # run clippy for each feature flag configuration
      - run: cargo clippy --features metrics
      - run: cargo clippy --no-default-features
      
      - run: cargo test
      